groups:
  - name: "instances"
    rules:
      - alert: "InstanceDown"
        expr: "up == 0"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: 'Instance {{ $labels.instance_name }} down'
          description: '{{ $labels.instance_name }} of job {{ $labels.job }} has been down for more than 1 minute.'
