groups:
  - name: "systemd"
    rules:
      - alert: "SystemdServiceCrashed"
        expr: 'node_systemd_unit_state{state="failed", name!="dnf-makecache.service"} == 1'
        labels:
          severity: "critical"
        annotations:
          summary: 'Systemd service crashed.'
          description: 'Systemd service {{ $labels.name }} crashed on {{ $labels.instance_name }}.'
