- name: "Add cilium Helm repo"
  tags: ["cilium-install"]
  kubernetes.core.helm_repository:
    name: "cilium"
    repo_url: "https://helm.cilium.io"
  check_mode: false
  delegate_to: "localhost"
  run_once: true
  become: false

- ansible.builtin.import_tasks: "cilium-values.yml"
  tags: ["cilium-install"]

- ansible.builtin.import_tasks: "_helm-preflight.yml"
  tags: ["cilium-install"]
  vars:
    _helm_preflight_release_name: "cilium"
    _helm_preflight_release_namespace: "{{ k8s_addons_cilium_namespace }}"

- name: "Install/upgrade cilium chart"
  tags: ["cilium-install"]
  kubernetes.core.helm:
    kubeconfig: "{{ k8s_addons_kubeconfig }}"
    name: "cilium"
    chart_ref: "cilium/cilium"
    chart_version: "{{ k8s_addons_cilium_chart_version }}"
    release_namespace: "{{ k8s_addons_cilium_namespace }}"
    create_namespace: true
    wait: true
    atomic: true
    timeout: "{{ k8s_addons_cilium_chart_timeout }}"
    values: "{{ _cilium_helm_values }}"
  delegate_to: "localhost"
  run_once: true
  become: false
