- ansible.builtin.import_tasks: "_peers.yml"

- name: "Open the node to the scheduler"
  tags: ["uncordon"]
  ansible.builtin.command:
    argv: ["/usr/local/bin/k3s", "kubectl", "uncordon", "{{ k3s_node_name }}"]
  delegate_to: "{{ k3s_cluster_peers[0] }}"
  changed_when: true
