- ansible.builtin.import_tasks: "_validate.yml"

- name: "Back up data paths"
  tags: ["backup"]
  ansible.builtin.include_role:
    name: "hacode.infra.common"
    tasks_from: "backup"
    apply:
      tags: ["backup"]
  vars:
    hacode_backup_paths: "{{ _app_data_paths_abs }}"
    hacode_backup_name: "{{ inventory_hostname }}_{{ app_project }}"
    hacode_backup_local_dir: "{{ app_backup_local_dir }}"
    hacode_backup_remote_dir: "{{ app_backup_remote_dir }}"
    hacode_backup_exclude_paths: >-
      {{ app_backup_exclude | map('regex_replace', '^(.*)', app_content_dir ~ '/\1') | list }}
    hacode_backup_exclusion_patterns: "{{ app_backup_exclusion_patterns }}"
  when: "app_data_paths | length > 0"
