# PHP files

index index.php index.html;

location ~ /\. {
    deny all;
}

location ~ ^/log/ {
    deny all;
}

location ~ \.php$ {
    fastcgi_pass unix:/run/php-fpm/www.sock;
    include         fastcgi_params;
    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
}
