- name: "Gather Facts"
  tags: ["install"]
  ansible.builtin.setup:
    gather_subset:
      - "architecture"
      - "mounts"
  when: "ansible_architecture is not defined or ansible_mounts is not defined"

- name: "Install Node Exporter"
  tags: ["install"]
  vars:
    node_exporter_version: "1.9.1"
    node_exporter_web_listen_address: "{{ node_exporter_web_listen_ip }}:{{ node_exporter_web_listen_port }}"
  ansible.builtin.include_role:
    name: "prometheus.prometheus.node_exporter"
    apply:
      tags: ["install"]

- name: "Manage Node Exporter port on RHEL family"
  when: "ansible_os_family == 'RedHat'"
  tags: ["firewall"]
  block:
    - name: "Enable Node Exporter port in firewall"
      ansible.posix.firewalld:
        port: "{{ node_exporter_web_listen_port }}/tcp"
        permanent: true
        state: "enabled"
      register: "ne_fw_port"

    - name: "Reload firewall"
      ansible.builtin.systemd:
        name: "firewalld"
        state: "reloaded"
      when: "ne_fw_port is changed or (force | default(false) | bool)"
