# Enable mouse
set -g mouse on

# Scrollback buffer
set -g history-limit 100000

# Enable scroll in fullscreen apps
bind-key -n WheelUpPane if -F '#{pane_in_mode}' \
  'send-keys -M' \
  'if -F "#{alternate_on}" "send-keys -N 1 Up" "copy-mode -e; send-keys -M"'
bind-key -n WheelDownPane if -F '#{pane_in_mode}' \
  'send-keys -M' \
  'if -F "#{alternate_on}" "send-keys -N 1 Down" "send-keys -M"'

# Selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# TERM
set -g default-terminal "tmux-256color"

# truecolor / 24-bit colors
set -as terminal-features ",xterm*:RGB"

# pass-through special escape sequences
set -g allow-passthrough on

# extended key combinations
set -s extended-keys on
set -as terminal-features ",xterm*:extkeys"

# Ctrl+Left: previous window
bind-key -n C-Left previous-window

# Ctrl+Right: next window
bind-key -n C-Right next-window

# Set agent socket
setenv -g SSH_AUTH_SOCK $HOME/.ssh/auth.sock
